### ISSUE TITLE
Documentation eCommerce Tag - datalayer-variable

### ISSUE THREAD

**Issue by utrautmann** [openmost/TagManagerExtended#3]
Hello, 
great job you did here. Thank you very much for expanding the Tag Manager.

I have a question about the eCommerce tracking tag.
You write in the Tag Manager: "Create a {⁣{Ecommerce}} data layer variable to collect the "ecommerce" key in _mtm."
But how exactly should the data layer variables be named?
For example, to track an order I have to specify the following variables in the datalayer:
_orderId, revenue, subTotal, tax, shipping, discount_

Or did you use exactly the variable wording that Matomo also uses in its documentation for the e-commerce functions?

Can you give an example please? Thank you very much.

**Comment by ronan-hello** [comment]
Hello,

Thank you for your comment.

In order to use this tag, you should use the Google Analytics 4 dataLayer structure.
You have to create an `{{Ecommerce}}` variable based on the `ecommerce` key in the `dataLayer`.
You can follow this tutorial I wrote (in french, but soon in english) : https://ronan-hello.fr/series/matomo/ecommerce-matomo-tag-manager

Regards,
Ronan
